#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-ExtUtils-Depends
Version  : 0.8001
Release  : 36
URL      : https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-Depends-0.8001.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-Depends-0.8001.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-ExtUtils-Depends-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
ExtUtils::Depends - Easily build XS extensions that depend on XS
extensions

%package dev
Summary: dev components for the perl-ExtUtils-Depends package.
Group: Development
Provides: perl-ExtUtils-Depends-devel = %{version}-%{release}
Requires: perl-ExtUtils-Depends = %{version}-%{release}

%description dev
dev components for the perl-ExtUtils-Depends package.


%package perl
Summary: perl components for the perl-ExtUtils-Depends package.
Group: Default
Requires: perl-ExtUtils-Depends = %{version}-%{release}

%description perl
perl components for the perl-ExtUtils-Depends package.


%prep
%setup -q -n ExtUtils-Depends-0.8001
cd %{_builddir}/ExtUtils-Depends-0.8001

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/ExtUtils::Depends.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
